<?php

namespace Database\Seeders;

use App\Modules\Search\Models\Destination;
use Illuminate\Database\Seeder;

class DestinationSeeder extends Seeder
{
    public function run(): void
    {
        $destinations = [
            ['name' => 'Bangkok', 'slug' => 'bangkok', 'code' => 'BKK', 'country' => 'Thailand', 'country_code' => 'THA', 'timezone' => 'Asia/Bangkok', 'latitude' => 13.7563, 'longitude' => 100.5018, 'description' => 'Thailand\'s vibrant capital city, known for ornate shrines, bustling street life, and the Grand Palace.', 'avg_price' => 89, 'is_popular' => true, 'is_featured' => true, 'weather' => ['avg_temp' => '28-35°C', 'best_time' => 'Nov-Feb', 'rainy_season' => 'Jun-Oct'], 'highlights' => ['Grand Palace & Wat Phra Kaew', 'Chatuchak Weekend Market', 'Street food tours', 'Chao Phraya River cruise', 'Khao San Road nightlife'], 'travel_tips' => ['Use the BTS Skytrain to avoid traffic', 'Dress modestly when visiting temples', 'Negotiate taxi fares before getting in', 'Try the local pad thai and mango sticky rice']],
            ['name' => 'Singapore', 'slug' => 'singapore', 'code' => 'SIN', 'country' => 'Singapore', 'country_code' => 'SGP', 'timezone' => 'Asia/Singapore', 'latitude' => 1.3521, 'longitude' => 103.8198, 'description' => 'A modern city-state known for its futuristic architecture, diverse cuisine, and Gardens by the Bay.', 'avg_price' => 120, 'is_popular' => true, 'is_featured' => true, 'weather' => ['avg_temp' => '25-32°C', 'best_time' => 'Feb-Apr', 'rainy_season' => 'Nov-Jan'], 'highlights' => ['Marina Bay Sands', 'Gardens by the Bay', 'Sentosa Island', 'Hawker centres', 'Orchard Road shopping'], 'travel_tips' => ['Get an EZ-Link card for public transport', 'Chewing gum is banned', 'Visit hawker centres for affordable food', 'The MRT system is excellent']],
            ['name' => 'Bali', 'slug' => 'bali', 'code' => 'DPS', 'country' => 'Indonesia', 'country_code' => 'IDN', 'timezone' => 'Asia/Makassar', 'latitude' => -8.3405, 'longitude' => 115.092, 'description' => 'Indonesia\'s most famous island, known for its forested volcanic mountains, rice paddies, and beaches.', 'avg_price' => 75, 'is_popular' => true, 'is_featured' => true, 'weather' => ['avg_temp' => '27-30°C', 'best_time' => 'Apr-Oct', 'rainy_season' => 'Nov-Mar'], 'highlights' => ['Ubud rice terraces', 'Tanah Lot temple', 'Seminyak beach clubs', 'Mount Batur sunrise trek', 'Uluwatu cliff temple'], 'travel_tips' => ['Rent a scooter for getting around', 'Bargain at local markets', 'Visit temples in the morning to avoid crowds', 'Try local warung restaurants for authentic food']],
            ['name' => 'Kuala Lumpur', 'slug' => 'kuala-lumpur', 'code' => 'KUL', 'country' => 'Malaysia', 'country_code' => 'MYS', 'timezone' => 'Asia/Kuala_Lumpur', 'latitude' => 3.139, 'longitude' => 101.6869, 'description' => 'Malaysia\'s capital featuring the iconic Petronas Twin Towers and diverse food scene.', 'avg_price' => 65, 'is_popular' => true, 'is_featured' => false, 'weather' => ['avg_temp' => '27-33°C', 'best_time' => 'May-Jul', 'rainy_season' => 'Oct-Mar'], 'highlights' => ['Petronas Twin Towers', 'Batu Caves', 'Jalan Alor food street', 'Central Market', 'KLCC Park'], 'travel_tips' => ['Use Grab for affordable rides', 'Visit Batu Caves early morning', 'Try nasi lemak for breakfast']],
            ['name' => 'Ho Chi Minh City', 'slug' => 'ho-chi-minh-city', 'code' => 'SGN', 'country' => 'Vietnam', 'country_code' => 'VNM', 'timezone' => 'Asia/Ho_Chi_Minh', 'latitude' => 10.8231, 'longitude' => 106.6297, 'description' => 'Vietnam\'s largest city, known for its French colonial architecture, vibrant street life, and pho.', 'avg_price' => 55, 'is_popular' => true, 'is_featured' => false, 'weather' => ['avg_temp' => '25-35°C', 'best_time' => 'Dec-Apr', 'rainy_season' => 'May-Nov'], 'highlights' => ['Cu Chi Tunnels', 'War Remnants Museum', 'Ben Thanh Market', 'Notre-Dame Cathedral', 'Mekong Delta day trip'], 'travel_tips' => ['Cross streets confidently and slowly', 'Drink iced Vietnamese coffee', 'Use Grab for transport']],
            ['name' => 'Hanoi', 'slug' => 'hanoi', 'code' => 'HAN', 'country' => 'Vietnam', 'country_code' => 'VNM', 'timezone' => 'Asia/Ho_Chi_Minh', 'latitude' => 21.0285, 'longitude' => 105.8542, 'description' => 'Vietnam\'s capital, a centuries-old city known for its rich culture, ancient architecture, and street food.', 'avg_price' => 50, 'is_popular' => true, 'is_featured' => false, 'weather' => ['avg_temp' => '17-33°C', 'best_time' => 'Oct-Dec', 'rainy_season' => 'May-Sep'], 'highlights' => ['Old Quarter', 'Hoan Kiem Lake', 'Ho Chi Minh Mausoleum', 'Water puppet theatre', 'Street food walking tours'], 'travel_tips' => ['Walk the Old Quarter on foot', 'Try bun cha and egg coffee']],
            ['name' => 'Manila', 'slug' => 'manila', 'code' => 'MNL', 'country' => 'Philippines', 'country_code' => 'PHL', 'timezone' => 'Asia/Manila', 'latitude' => 14.5995, 'longitude' => 120.9842, 'description' => 'Capital of the Philippines, a bustling metropolis with rich history and beautiful bay sunsets.', 'avg_price' => 70, 'is_popular' => false, 'is_featured' => false, 'weather' => ['avg_temp' => '26-34°C', 'best_time' => 'Dec-May', 'rainy_season' => 'Jun-Nov'], 'highlights' => ['Intramuros historic district', 'Manila Bay sunset', 'Rizal Park', 'SM Mall of Asia'], 'travel_tips' => ['Traffic can be extreme, plan accordingly', 'Use Grab for safe transport']],
            ['name' => 'Phnom Penh', 'slug' => 'phnom-penh', 'code' => 'PNH', 'country' => 'Cambodia', 'country_code' => 'KHM', 'timezone' => 'Asia/Phnom_Penh', 'latitude' => 11.5564, 'longitude' => 104.9282, 'description' => 'Cambodia\'s capital, where the Mekong and Tonlé Sap rivers meet, known for its royal palace and history.', 'avg_price' => 45, 'is_popular' => false, 'is_featured' => false, 'weather' => ['avg_temp' => '25-35°C', 'best_time' => 'Nov-Feb', 'rainy_season' => 'May-Oct'], 'highlights' => ['Royal Palace', 'Tuol Sleng Museum', 'Central Market', 'Riverside promenade'], 'travel_tips' => ['USD is widely accepted', 'Tuk-tuks are the main transport']],
            ['name' => 'Siem Reap', 'slug' => 'siem-reap', 'code' => 'REP', 'country' => 'Cambodia', 'country_code' => 'KHM', 'timezone' => 'Asia/Phnom_Penh', 'latitude' => 13.3671, 'longitude' => 103.8448, 'description' => 'Gateway to the temples of Angkor, one of the most important archaeological sites in Southeast Asia.', 'avg_price' => 55, 'is_popular' => true, 'is_featured' => true, 'weather' => ['avg_temp' => '25-35°C', 'best_time' => 'Nov-Mar', 'rainy_season' => 'May-Oct'], 'highlights' => ['Angkor Wat sunrise', 'Ta Prohm temple', 'Pub Street', 'Tonlé Sap floating villages', 'Phare Circus'], 'travel_tips' => ['Buy a 3-day Angkor pass', 'Start temple visits at sunrise', 'Wear comfortable shoes and sun protection']],
            ['name' => 'Phuket', 'slug' => 'phuket', 'code' => 'HKT', 'country' => 'Thailand', 'country_code' => 'THA', 'timezone' => 'Asia/Bangkok', 'latitude' => 7.8804, 'longitude' => 98.3923, 'description' => 'Thailand\'s largest island, famous for its beautiful beaches, lively nightlife, and seafood.', 'avg_price' => 95, 'is_popular' => true, 'is_featured' => false, 'weather' => ['avg_temp' => '27-33°C', 'best_time' => 'Nov-Apr', 'rainy_season' => 'May-Oct'], 'highlights' => ['Patong Beach', 'Phi Phi Islands day trip', 'Old Phuket Town', 'Big Buddha', 'James Bond Island'], 'travel_tips' => ['Rent a scooter for exploring', 'Visit during dry season for best beaches']],
            ['name' => 'Chiang Mai', 'slug' => 'chiang-mai', 'code' => 'CNX', 'country' => 'Thailand', 'country_code' => 'THA', 'timezone' => 'Asia/Bangkok', 'latitude' => 18.7883, 'longitude' => 98.9853, 'description' => 'Northern Thailand\'s cultural capital, known for its ancient temples, night markets, and mountain scenery.', 'avg_price' => 60, 'is_popular' => true, 'is_featured' => false, 'weather' => ['avg_temp' => '20-36°C', 'best_time' => 'Nov-Feb', 'rainy_season' => 'Jun-Oct'], 'highlights' => ['Doi Suthep temple', 'Sunday Night Market', 'Elephant sanctuaries', 'Thai cooking classes', 'Old City temples'], 'travel_tips' => ['Visit an ethical elephant sanctuary', 'Try khao soi noodles']],
            ['name' => 'Luang Prabang', 'slug' => 'luang-prabang', 'code' => 'LPQ', 'country' => 'Laos', 'country_code' => 'LAO', 'timezone' => 'Asia/Vientiane', 'latitude' => 19.8856, 'longitude' => 102.1347, 'description' => 'A UNESCO World Heritage city in Laos, known for Buddhist monks\' alms procession and French colonial architecture.', 'avg_price' => 65, 'is_popular' => false, 'is_featured' => false, 'weather' => ['avg_temp' => '20-35°C', 'best_time' => 'Oct-Apr', 'rainy_season' => 'May-Sep'], 'highlights' => ['Monks alms giving ceremony', 'Kuang Si Falls', 'Night market', 'Pak Ou Caves', 'Royal Palace Museum'], 'travel_tips' => ['Wake up early for the alms ceremony', 'Bring cash as ATMs are limited']],
            ['name' => 'Yangon', 'slug' => 'yangon', 'code' => 'RGN', 'country' => 'Myanmar', 'country_code' => 'MMR', 'timezone' => 'Asia/Yangon', 'latitude' => 16.8661, 'longitude' => 96.1951, 'description' => 'Myanmar\'s largest city, home to the golden Shwedagon Pagoda and colonial-era architecture.', 'avg_price' => 70, 'is_popular' => false, 'is_featured' => false, 'weather' => ['avg_temp' => '25-37°C', 'best_time' => 'Nov-Feb', 'rainy_season' => 'May-Oct'], 'highlights' => ['Shwedagon Pagoda', 'Bogyoke Market', 'Kandawgyi Lake', 'Colonial downtown walk'], 'travel_tips' => ['Remove shoes at temples', 'Cash is preferred, bring USD']],
            ['name' => 'Jakarta', 'slug' => 'jakarta', 'code' => 'CGK', 'country' => 'Indonesia', 'country_code' => 'IDN', 'timezone' => 'Asia/Jakarta', 'latitude' => -6.2088, 'longitude' => 106.8456, 'description' => 'Indonesia\'s massive capital, a melting pot of cultures with modern skyscrapers and historic neighborhoods.', 'avg_price' => 60, 'is_popular' => false, 'is_featured' => false, 'weather' => ['avg_temp' => '26-34°C', 'best_time' => 'Jun-Sep', 'rainy_season' => 'Oct-Mar'], 'highlights' => ['National Monument (Monas)', 'Old Town (Kota Tua)', 'Ancol Dreamland', 'Thousand Islands day trip'], 'travel_tips' => ['Traffic is notoriously bad, use MRT when possible']],
            ['name' => 'Colombo', 'slug' => 'colombo', 'code' => 'CMB', 'country' => 'Sri Lanka', 'country_code' => 'LKA', 'timezone' => 'Asia/Colombo', 'latitude' => 6.9271, 'longitude' => 79.8612, 'description' => 'Sri Lanka\'s bustling capital, a blend of modern high-rises and colonial buildings by the Indian Ocean.', 'avg_price' => 80, 'is_popular' => false, 'is_featured' => false, 'weather' => ['avg_temp' => '26-31°C', 'best_time' => 'Dec-Mar', 'rainy_season' => 'May-Sep'], 'highlights' => ['Gangaramaya Temple', 'Galle Face Green', 'Pettah Market', 'National Museum'], 'travel_tips' => ['Try Ceylon tea everywhere', 'Use tuk-tuks for short distances']],
            ['name' => 'Taipei', 'slug' => 'taipei', 'code' => 'TPE', 'country' => 'Taiwan', 'country_code' => 'TWN', 'timezone' => 'Asia/Taipei', 'latitude' => 25.033, 'longitude' => 121.5654, 'description' => 'Taiwan\'s capital, famous for its night markets, Taipei 101 skyscraper, and incredible food scene.', 'avg_price' => 110, 'is_popular' => true, 'is_featured' => false, 'weather' => ['avg_temp' => '16-30°C', 'best_time' => 'Sep-Nov', 'rainy_season' => 'May-Jun'], 'highlights' => ['Taipei 101', 'Shilin Night Market', 'Jiufen village', 'Elephant Mountain hike', 'Din Tai Fung dumplings'], 'travel_tips' => ['Get an EasyCard for MRT', 'Night markets are a must-visit']],
            ['name' => 'Hong Kong', 'slug' => 'hong-kong', 'code' => 'HKG', 'country' => 'Hong Kong', 'country_code' => 'HKG', 'timezone' => 'Asia/Hong_Kong', 'latitude' => 22.3193, 'longitude' => 114.1694, 'description' => 'A vibrant city where East meets West, known for its skyline, dim sum, and Victoria Harbour.', 'avg_price' => 130, 'is_popular' => true, 'is_featured' => false, 'weather' => ['avg_temp' => '16-32°C', 'best_time' => 'Oct-Dec', 'rainy_season' => 'Jun-Aug'], 'highlights' => ['Victoria Peak', 'Star Ferry', 'Temple Street Night Market', 'Big Buddha Lantau', 'Dim sum tour'], 'travel_tips' => ['Get an Octopus card', 'Take the Star Ferry for stunning views']],
            ['name' => 'Da Nang', 'slug' => 'da-nang', 'code' => 'DAD', 'country' => 'Vietnam', 'country_code' => 'VNM', 'timezone' => 'Asia/Ho_Chi_Minh', 'latitude' => 16.0544, 'longitude' => 108.2022, 'description' => 'A coastal city in central Vietnam known for its sandy beaches, Ba Na Hills, and the Golden Bridge.', 'avg_price' => 45, 'is_popular' => true, 'is_featured' => false, 'weather' => ['avg_temp' => '24-34°C', 'best_time' => 'Feb-May', 'rainy_season' => 'Sep-Dec'], 'highlights' => ['Golden Bridge at Ba Na Hills', 'My Khe Beach', 'Marble Mountains', 'Dragon Bridge', 'Hoi An day trip'], 'travel_tips' => ['Rent a motorbike to explore', 'Visit Hoi An ancient town nearby']],
            ['name' => 'Penang', 'slug' => 'penang', 'code' => 'PEN', 'country' => 'Malaysia', 'country_code' => 'MYS', 'timezone' => 'Asia/Kuala_Lumpur', 'latitude' => 5.4141, 'longitude' => 100.3288, 'description' => 'A Malaysian island state known as the food capital of Asia, with UNESCO heritage in George Town.', 'avg_price' => 50, 'is_popular' => false, 'is_featured' => false, 'weather' => ['avg_temp' => '27-32°C', 'best_time' => 'Dec-Mar', 'rainy_season' => 'Apr-Nov'], 'highlights' => ['George Town street art', 'Penang Hill', 'Kek Lok Si Temple', 'Hawker food tour', 'Clan Jetties'], 'travel_tips' => ['Penang is a food paradise, eat everywhere', 'Walk around George Town for street art']],
            ['name' => 'Boracay', 'slug' => 'boracay', 'code' => 'MPH', 'country' => 'Philippines', 'country_code' => 'PHL', 'timezone' => 'Asia/Manila', 'latitude' => 11.9674, 'longitude' => 121.9248, 'description' => 'A small Philippine island famous for its white-sand beaches, crystal-clear waters, and vibrant nightlife.', 'avg_price' => 85, 'is_popular' => true, 'is_featured' => false, 'weather' => ['avg_temp' => '26-32°C', 'best_time' => 'Nov-May', 'rainy_season' => 'Jun-Oct'], 'highlights' => ['White Beach', 'Island hopping', 'Cliff diving at Ariel\'s Point', 'D\'Mall shopping', 'Puka Shell Beach'], 'travel_tips' => ['Book hotels on Station 1 for quieter beach', 'Environmental fee required on arrival']],
        ];

        foreach ($destinations as $dest) {
            Destination::create($dest);
        }
    }
}
